# Generated by Django 4.2.4 on 2023-12-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='nome',
        ),
    ]
