# Generated by Django 4.2.7 on 2023-12-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_pessoa_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='rua',
        ),
    ]
