# Generated by Django 4.2.7 on 2023-12-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_remove_endereco_bairro_remove_endereco_cidade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
